# -*- coding: utf-8 -*-
"""HASH-ALGORITHM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KeHRL3pBcMwZS3_S0iqSmx5HWHKvllBH
"""

import hashlib

text="The greatest glory in living lies not in never falling,but in rising every time we fall.-Nelson Mandela"

"""We gonna use three different hash algorithms on this text string
1.MD5 2.SHA-2 3.SHA-3

**1.MD5**
"""

hash_obj=hashlib.md5(text.encode())

md5_hash=hash_obj.hexdigest()

print(md5_hash)

"""**2.SHA-2**"""

hash_obj=hashlib.sha256(text.encode())

sha256_hash=hash_obj.hexdigest()

print(sha256_hash)

hash_obj=hashlib.sha512(text.encode())

sha512_hash=hash_obj.hexdigest()

print(sha512_hash)

"""**3.SHA-3**"""

hash_obj=hashlib.blake2s(text.encode())

blake2s_hash=hash_obj.hexdigest()

print(blake2s_hash)

hash_obj=hashlib.blake2b(text.encode())

blake2b_hash=hash_obj.hexdigest()

print(blake2b_hash)