# -*- coding: utf-8 -*-
"""MD5 HASH.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_aWH52aSyE-MprAbqafhYitIgvzGkwWm
"""

import hashlib

text="The greatest glory in living lies not in never falling,but in rising every time we fall.-Nelson Mandela"

hash_obj=hashlib.md5(text.encode())

md5_hash=hash_obj.hexdigest()

print(md5_hash)